### ISSUE TITLE
Stand up instance of Verily data explorer with the ENCODE data

### ISSUE THREAD

**Issue by clare-b** [broadinstitute/gdr-ingest#1]
As a researcher in Saturn, I'd like to explore the ENCODE dataset, filter to specific samples and then send those samples to a workspace so that I can analyze them along with other datasets.

Assumptions:
* Current data explorer will implement a "send to Saturn" button
* Current data explorer has the required filtering functionality 

Goals:
* We can demo the current explorer with the ENCODE data for end users/stakeholders to see where the gaps are
* Having this data hooked up with a data explorer will allow us to make it available more broadly in Saturn

Requirements:
* All data is still kept private for now, we are not broadly distributing the data until we have permission
* The data explorer is powered by all of the ENCODE ChIP-Seq data and we can use the explorer to filter the data

**Comment by danxmoran** [comment]
I've got an instance running [here](http://broad-gdr-encode.appspot.com/). To get it working, I had to manually denormalize the donors data into the files data. When I tried to denormalize in the opposite direction, the indexer failed with the error:
```
2018100914:42:09    base.py:83 INFO HEAD http://10.128.0.5:9200/encode [status:200 request:0.003s]
2018100914:42:09 indexer_util.py:99 INFO Using existing encode index at http://10.128.0.5:9200/.
2018100914:42:09 indexer.py:107 INFO Adding neseted mappings to encode.
2018100914:42:09    base.py:83 INFO PUT http://10.128.0.5:9200/encode/_mapping/type [status:200 request:0.006s]
2018100914:42:09 indexer.py:195 INFO Indexing broad-gdr-encode-storage.encode_2018_10_07.donors_denormalized into encode.
Index name: encode
Traceback (most recent call last):
  File "/app/indexer.py", line 266, in <module>
Elasticsearch took 0 seconds to come up.
    main()
  File "/app/indexer.py", line 261, in main
    sample_id_column, sample_file_columns)
  File "/app/indexer.py", line 199, in index_table
    df = client.list_rows(table).to_dataframe()
  File "/usr/local/lib/python2.7/site-packages/google/cloud/bigquery/table.py", line 1169, in to_dataframe
    rows = [row.values() for row in iter(self)]
  File "/usr/local/lib/python2.7/site-packages/google/api_core/page_iterator.py", line 199, in _items_iter
    for page in self._page_iter(increment=False):
  File "/usr/local/lib/python2.7/site-packages/google/api_core/page_iterator.py", line 236, in _page_iter
    page = self._next_page()
  File "/usr/local/lib/python2.7/site-packages/google/api_core/page_iterator.py", line 349, in _next_page
    response = self._get_next_page_response()
  File "/usr/local/lib/python2.7/site-packages/google/cloud/bigquery/table.py", line 1140, in _get_next_page_response
    query_params=params)
  File "/usr/local/lib/python2.7/site-packages/google/cloud/bigquery/client.py", line 331, in _call_api
    return call()
  File "/usr/local/lib/python2.7/site-packages/google/api_core/retry.py", line 260, in retry_wrapped_func
    on_error=on_error,
  File "/usr/local/lib/python2.7/site-packages/google/api_core/retry.py", line 177, in retry_target
    return target()
  File "/usr/local/lib/python2.7/site-packages/google/cloud/_http.py", line 293, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.BadRequest: 400 GET https://www.googleapis.com/bigquery/v2/projects/broad-gdr-encode-storage/datasets/encode_2018_10_07/tables/donors_denormalized/data?pageToken=BHZDCR2ZMYAQAAASAUIIBAEAAUNAOCH5AEIKBDIGED77777777777737FIAA%3D%3D%3D%3D: API limit exceeded: Unable to return a row that exceeds the API limits. To retrieve the row, export the table.
```
The explorer also doesn't seem to find possible values for nested structs that aren't special-cased as a "samples" field on indexing.
